version: '3.8'

services:
  postgres:
    image: postgres:16.1
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: b2b-endpoint
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user", "-d", "b2b-endpoint" ]
      interval: 1s
      timeout: 5s
      retries: 10

  flyway:
    container_name: flyway-b2b-endpoint-service
    image: flyway/flyway:latest
    command:
      -url=jdbc:postgresql://postgres:5432/b2b-endpoint -user=user -password=password -validateMigrationNaming="true" -connectRetries=60 migrate
    volumes:
      - ../../migrations:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy

networks:
  default:
    name: network-b2b-endpoint-service
