// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: protocol/proto/admin_profile.proto

package profile

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminProfileService_DeleteSubUser_FullMethodName = "/profileAdmin.adminProfileService/DeleteSubUser"
)

// AdminProfileServiceClient is the client API for AdminProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminProfileServiceClient interface {
	DeleteSubUser(ctx context.Context, in *DeleteSubUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type adminProfileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminProfileServiceClient(cc grpc.ClientConnInterface) AdminProfileServiceClient {
	return &adminProfileServiceClient{cc}
}

func (c *adminProfileServiceClient) DeleteSubUser(ctx context.Context, in *DeleteSubUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AdminProfileService_DeleteSubUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminProfileServiceServer is the server API for AdminProfileService service.
// All implementations must embed UnimplementedAdminProfileServiceServer
// for forward compatibility.
type AdminProfileServiceServer interface {
	DeleteSubUser(context.Context, *DeleteSubUserRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedAdminProfileServiceServer()
}

// UnimplementedAdminProfileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminProfileServiceServer struct{}

func (UnimplementedAdminProfileServiceServer) DeleteSubUser(context.Context, *DeleteSubUserRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSubUser not implemented")
}
func (UnimplementedAdminProfileServiceServer) mustEmbedUnimplementedAdminProfileServiceServer() {}
func (UnimplementedAdminProfileServiceServer) testEmbeddedByValue()                             {}

// UnsafeAdminProfileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminProfileServiceServer will
// result in compilation errors.
type UnsafeAdminProfileServiceServer interface {
	mustEmbedUnimplementedAdminProfileServiceServer()
}

func RegisterAdminProfileServiceServer(s grpc.ServiceRegistrar, srv AdminProfileServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminProfileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminProfileService_ServiceDesc, srv)
}

func _AdminProfileService_DeleteSubUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSubUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminProfileServiceServer).DeleteSubUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminProfileService_DeleteSubUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminProfileServiceServer).DeleteSubUser(ctx, req.(*DeleteSubUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminProfileService_ServiceDesc is the grpc.ServiceDesc for AdminProfileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminProfileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "profileAdmin.adminProfileService",
	HandlerType: (*AdminProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteSubUser",
			Handler:    _AdminProfileService_DeleteSubUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocol/proto/admin_profile.proto",
}
