run:
  timeout: 3m

linters:
  enable:
    - bodyclose
    - contextcheck
    - copyloopvar
    - dupl
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - gocritic
    - godot
    - gofmt
    - gofumpt
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testifylint
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl

linters-settings:
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
      - pattern: 'a[b:len(a)]'
        replacement: 'a[b:]'
  mnd:
    ignored-functions:
      - strconv.*
  tagalign:
    align: false
    order:
      - config
      - json
      - yaml
  tagliatelle:
    case:
      rules:
        yaml: snake
        json: snake

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - noctx
    - linters:
        - lll
      source: "^//go:generate"
    - linters:
        - lll
      source: "^// http(s)://.*" # ignore long links in comments
    - linters:
        - lll
      source: "// (TODO|NOTE):" # ignore long todos and notes
    - text: "unused-parameter: parameter 'ctx' seems to be unused, consider removing or renaming it as _"
      linters:
        - revive
    - path: '(.+)_test\.go'
      text: "unused-parameter: parameter '(.+)' seems to be unused, consider removing or renaming it as _"
      linters:
        - revive
    - path: 'internal/repository/pg' # we use single db for tests, so we cannot run them in parallel
      linters:
        - paralleltest
