// Code generated by mockery v2.43.2. DO NOT EDIT.

package worker

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTaskCronWorker is an autogenerated mock type for the TaskCronWorker type
type MockTaskCronWorker struct {
	mock.Mock
}

type MockTaskCronWorker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskCronWorker) EXPECT() *MockTaskCronWorker_Expecter {
	return &MockTaskCronWorker_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *MockTaskCronWorker) Execute(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskCronWorker_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockTaskCronWorker_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskCronWorker_Expecter) Execute(ctx interface{}) *MockTaskCronWorker_Execute_Call {
	return &MockTaskCronWorker_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *MockTaskCronWorker_Execute_Call) Run(run func(ctx context.Context)) *MockTaskCronWorker_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTaskCronWorker_Execute_Call) Return(_a0 error) *MockTaskCronWorker_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskCronWorker_Execute_Call) RunAndReturn(run func(context.Context) error) *MockTaskCronWorker_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskCronWorker creates a new instance of MockTaskCronWorker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskCronWorker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskCronWorker {
	mock := &MockTaskCronWorker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
