// Code generated by mockery v2.46.3. DO NOT EDIT.

package repository

import (
	context "context"

	model "code.emcdtech.com/b2b/swap/model"
	mock "github.com/stretchr/testify/mock"
)

// MockTransfer is an autogenerated mock type for the Transfer type
type MockTransfer struct {
	mock.Mock
}

type MockTransfer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransfer) EXPECT() *MockTransfer_Expecter {
	return &MockTransfer_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, transfer
func (_m *MockTransfer) Add(ctx context.Context, transfer *model.InternalTransfer) error {
	ret := _m.Called(ctx, transfer)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.InternalTransfer) error); ok {
		r0 = rf(ctx, transfer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransfer_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockTransfer_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - transfer *model.InternalTransfer
func (_e *MockTransfer_Expecter) Add(ctx interface{}, transfer interface{}) *MockTransfer_Add_Call {
	return &MockTransfer_Add_Call{Call: _e.mock.On("Add", ctx, transfer)}
}

func (_c *MockTransfer_Add_Call) Run(run func(ctx context.Context, transfer *model.InternalTransfer)) *MockTransfer_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.InternalTransfer))
	})
	return _c
}

func (_c *MockTransfer_Add_Call) Return(_a0 error) *MockTransfer_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransfer_Add_Call) RunAndReturn(run func(context.Context, *model.InternalTransfer) error) *MockTransfer_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function with given fields: ctx, filter
func (_m *MockTransfer) Find(ctx context.Context, filter *model.InternalTransferFilter) (model.InternalTransfers, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 model.InternalTransfers
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.InternalTransferFilter) (model.InternalTransfers, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.InternalTransferFilter) model.InternalTransfers); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.InternalTransfers)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.InternalTransferFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransfer_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockTransfer_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *model.InternalTransferFilter
func (_e *MockTransfer_Expecter) Find(ctx interface{}, filter interface{}) *MockTransfer_Find_Call {
	return &MockTransfer_Find_Call{Call: _e.mock.On("Find", ctx, filter)}
}

func (_c *MockTransfer_Find_Call) Run(run func(ctx context.Context, filter *model.InternalTransferFilter)) *MockTransfer_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.InternalTransferFilter))
	})
	return _c
}

func (_c *MockTransfer_Find_Call) Return(_a0 model.InternalTransfers, _a1 error) *MockTransfer_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransfer_Find_Call) RunAndReturn(run func(context.Context, *model.InternalTransferFilter) (model.InternalTransfers, error)) *MockTransfer_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindOne provides a mock function with given fields: ctx, filter
func (_m *MockTransfer) FindOne(ctx context.Context, filter *model.InternalTransferFilter) (*model.InternalTransfer, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindOne")
	}

	var r0 *model.InternalTransfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.InternalTransferFilter) (*model.InternalTransfer, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.InternalTransferFilter) *model.InternalTransfer); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.InternalTransfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.InternalTransferFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransfer_FindOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOne'
type MockTransfer_FindOne_Call struct {
	*mock.Call
}

// FindOne is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *model.InternalTransferFilter
func (_e *MockTransfer_Expecter) FindOne(ctx interface{}, filter interface{}) *MockTransfer_FindOne_Call {
	return &MockTransfer_FindOne_Call{Call: _e.mock.On("FindOne", ctx, filter)}
}

func (_c *MockTransfer_FindOne_Call) Run(run func(ctx context.Context, filter *model.InternalTransferFilter)) *MockTransfer_FindOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.InternalTransferFilter))
	})
	return _c
}

func (_c *MockTransfer_FindOne_Call) Return(_a0 *model.InternalTransfer, _a1 error) *MockTransfer_FindOne_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransfer_FindOne_Call) RunAndReturn(run func(context.Context, *model.InternalTransferFilter) (*model.InternalTransfer, error)) *MockTransfer_FindOne_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, internalTransfer, filter, partial
func (_m *MockTransfer) Update(ctx context.Context, internalTransfer *model.InternalTransfer, filter *model.InternalTransferFilter, partial *model.InternalTransferPartial) error {
	ret := _m.Called(ctx, internalTransfer, filter, partial)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.InternalTransfer, *model.InternalTransferFilter, *model.InternalTransferPartial) error); ok {
		r0 = rf(ctx, internalTransfer, filter, partial)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransfer_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTransfer_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - internalTransfer *model.InternalTransfer
//   - filter *model.InternalTransferFilter
//   - partial *model.InternalTransferPartial
func (_e *MockTransfer_Expecter) Update(ctx interface{}, internalTransfer interface{}, filter interface{}, partial interface{}) *MockTransfer_Update_Call {
	return &MockTransfer_Update_Call{Call: _e.mock.On("Update", ctx, internalTransfer, filter, partial)}
}

func (_c *MockTransfer_Update_Call) Run(run func(ctx context.Context, internalTransfer *model.InternalTransfer, filter *model.InternalTransferFilter, partial *model.InternalTransferPartial)) *MockTransfer_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.InternalTransfer), args[2].(*model.InternalTransferFilter), args[3].(*model.InternalTransferPartial))
	})
	return _c
}

func (_c *MockTransfer_Update_Call) Return(_a0 error) *MockTransfer_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransfer_Update_Call) RunAndReturn(run func(context.Context, *model.InternalTransfer, *model.InternalTransferFilter, *model.InternalTransferPartial) error) *MockTransfer_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransfer creates a new instance of MockTransfer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransfer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransfer {
	mock := &MockTransfer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
