version: '3.8'

services:
  postgres-profile:
    image: postgres:14.7
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: profile
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user", "-d", "profile" ]
      interval: 1s
      timeout: 5s
      retries: 10

  flyway-profile:
    image: flyway/flyway:latest
    command:
      -url=jdbc:postgresql://postgres-profile:5432/profile -user=user -password=password -validateMigrationNaming="true" -connectRetries=60 migrate
    volumes:
      - ../../migrations:/flyway/sql
    depends_on:
      postgres-profile:
        condition: service_healthy

networks:
  default:
    name: network-profile-service
