include:
  - project: 'ci-tools/templates'
    file:
      - 'build/docker-build.yml'
      - 'deploy/docker-deploy.yml'
      - 'deploy/argo.yml'
      - 'tests/go-lint.yml'
      - 'deploy/migrate.yml'
  - project: 'ci-tools/templates'
    file: 'tests/go-unit.yml'

lint_tests:
  extends: .template_lint_tests

unit_tests:
  extends: .template_unit_tests

build_branch:
  extends: .template_branch_build

# на дев не катим, можем нарушить ограничение byBit limit API

migrate_stage:
  extends: .template_migrate_stage
deploy_stage:
  extends: .argo_template_deploy_stage



build_tag:
  extends: .template_tag_build

migrate_prod:
  extends: .template_migrate_prod
  when: manual
deploy_prod:
  extends: .template_deploy_prod
  when: manual

restart_prod_manual:
  extends: .template_restart_prod
