with-expecter: True
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_"}}
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
filename: "{{.InterfaceName|snakecase}}.go"
all: True
packages:
  code.emcdtech.com/b2b/swap:
    config:
      recursive: True