ALTER TABLE whitelabel
    ADD COLUMN user_id INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN segment_id INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN origin VARCHAR NOT NULL DEFAULT '',
    ADD COLUMN prefix VARCHAR NOT NULL DEFAULT '',
    ADD COLUMN sender_email VARCHAR NOT NULL DEFAULT '',
    ADD COLUMN api_key VARCHAR NOT NULL DEFAULT '',
    ADD COLUMN url VARCHAR NOT NULL DEFAULT '',
    ADD COLUMN version INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN master_slave BOOLEAN DEFAULT true,
    ADD COLUMN master_fee NUMERIC NOT NULL DEFAULT 0,
    ADD COLUMN is_active BOOLEAN DEFAULT true,
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT TIMEZONE('utc'::text, now()),
    ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT TIMEZONE('utc'::text, now());