
CREATE TABLE stratum (
    ref_id  INTEGER NOT NULL DEFAULT 0,
    coin        VARCHAR NOT NULL DEFAULT '',
    region      VARCHAR NOT NULL DEFAULT '',
    number      VARCHAR NOT NULL DEFAULT '',
    url         VARCHAR NOT NULL DEFAULT '',
    created_at  TIMESTAMP NOT NULL DEFAULT TIMEZONE('utc'::text, now()),
    updated_at  TIMESTAMP NOT NULL DEFAULT TIMEZONE('utc'::text, now())
);

INSERT INTO stratum
    (ref_id, coin, region, number, url, created_at, updated_at)
VALUES
    (1, 'btc', 'eu', '1', 'stratum+tcp://eu.emcd.io:3333', now(), now()),
    (1, 'btc', 'eu', '2', 'stratum+tcp://eu2.emcd.io:3333', now(), now()),
    (1, 'btc', 'eu', '3', 'stratum+tcp://gate.emcd.io:3333', now(), now()),
    (1, 'btc', 'ru', '1', 'stratum+tcp://gate.emcd.io:3333', now(), now()),
    (1, 'btc', 'ru', '2', 'stratum+tcp://eu.emcd.io:3333', now(), now()),
    (1, 'btc', 'ru', '3', 'stratum+tcp://kz.emcd.io:3333', now(), now()),
    (1, 'btc', 'cn', '1', 'stratum+tcp://cn.emcd.io:3333', now(), now()),
    (1, 'btc', 'cn', '2', 'stratum+tcp://eu.emcd.io:3333', now(), now()),
    (1, 'btc', 'cn', '3', 'stratum+tcp://gate.emcd.io:3333', now(), now()),
    (1, 'btc', 'us', '1', 'stratum+tcp://us.emcd.io:3333', now(), now()),
    (1, 'btc', 'us', '2', 'stratum+tcp://eu.emcd.io:3333', now(), now()),
    (1, 'btc', 'us', '3', 'stratum+tcp://gate.emcd.io:3333', now(), now()),
    (1, 'btc', 'ir', '1', 'stratum+tcp://ir.emcd.io:3333', now(), now()),
    (1, 'btc', 'kz', '1', 'stratum+tcp://kz.emcd.io:3333', now(), now()),
    (1, 'btc', 'kz', '2', 'stratum+tcp://gate.emcd.io:3333', now(), now()),
    (1, 'btc', 'kz', '3', 'stratum+tcp://eu.emcd.io:3333', now(), now()),

    (1, 'bch', 'eu', '1', 'stratum+tcp://eu.emcd.io:5555', now(), now()),
    (1, 'bch', 'eu', '2', 'stratum+tcp://eu2.emcd.io:5555', now(), now()),
    (1, 'bch', 'eu', '3', 'stratum+tcp://gate.emcd.io:5555', now(), now()),
    (1, 'bch', 'ru', '1', 'stratum+tcp://gate.emcd.io:5555', now(), now()),
    (1, 'bch', 'ru', '2', 'stratum+tcp://eu.emcd.io:5555', now(), now()),
    (1, 'bch', 'ru', '3', 'stratum+tcp://kz.emcd.io:5555', now(), now()),
    (1, 'bch', 'cn', '1', 'stratum+tcp://cn.emcd.io:5555', now(), now()),
    (1, 'bch', 'cn', '2', 'stratum+tcp://eu.emcd.io:5555', now(), now()),
    (1, 'bch', 'cn', '3', 'stratum+tcp://gate.emcd.io:5555', now(), now()),
    (1, 'bch', 'us', '1', 'stratum+tcp://us.emcd.io:5555', now(), now()),
    (1, 'bch', 'us', '2', 'stratum+tcp://eu.emcd.io:5555', now(), now()),
    (1, 'bch', 'us', '3', 'stratum+tcp://gate.emcd.io:5555', now(), now()),
    (1, 'bch', 'ir', '1', 'stratum+tcp://ir.emcd.io:5555', now(), now()),
    (1, 'bch', 'kz', '1', 'stratum+tcp://kz.emcd.io:5555', now(), now()),
    (1, 'bch', 'kz', '2', 'stratum+tcp://gate.emcd.io:5555', now(), now()),
    (1, 'bch', 'kz', '3', 'stratum+tcp://eu.emcd.io:5555', now(), now()),

    (1, 'ltc', 'eu', '1', 'stratum+tcp://eu.emcd.io:3434', now(), now()),
    (1, 'ltc', 'eu', '2', 'stratum+tcp://eu2.emcd.io:3434', now(), now()),
    (1, 'ltc', 'eu', '3', 'stratum+tcp://gate.emcd.io:3434', now(), now()),
    (1, 'ltc', 'ru', '1', 'stratum+tcp://gate.emcd.io:3434', now(), now()),
    (1, 'ltc', 'ru', '2', 'stratum+tcp://eu.emcd.io:3434', now(), now()),
    (1, 'ltc', 'ru', '3', 'stratum+tcp://kz.emcd.io:3434', now(), now()),
    (1, 'ltc', 'cn', '1', 'stratum+tcp://cn.emcd.io:3434', now(), now()),
    (1, 'ltc', 'cn', '2', 'stratum+tcp://eu.emcd.io:3434', now(), now()),
    (1, 'ltc', 'cn', '3', 'stratum+tcp://gate.emcd.io:3434', now(), now()),
    (1, 'ltc', 'us', '1', 'stratum+tcp://us.emcd.io:3434', now(), now()),
    (1, 'ltc', 'us', '2', 'stratum+tcp://eu.emcd.io:3434', now(), now()),
    (1, 'ltc', 'us', '3', 'stratum+tcp://gate.emcd.io:3434', now(), now()),
    (1, 'ltc', 'ir', '1', 'stratum+tcp://ir.emcd.io:3434', now(), now()),
    (1, 'ltc', 'kz', '1', 'stratum+tcp://kz.emcd.io:3434', now(), now()),
    (1, 'ltc', 'kz', '2', 'stratum+tcp://gate.emcd.io:3434', now(), now()),
    (1, 'ltc', 'kz', '3', 'stratum+tcp://eu.emcd.io:3434', now(), now()),

    (1, 'dash', 'eu', '1', 'stratum+tcp://eu.emcd.io:8888', now(), now()),
    (1, 'dash', 'eu', '2', 'stratum+tcp://eu2.emcd.io:8888', now(), now()),
    (1, 'dash', 'eu', '3', 'stratum+tcp://gate.emcd.io:8888', now(), now()),
    (1, 'dash', 'ru', '1', 'stratum+tcp://gate.emcd.io:8888', now(), now()),
    (1, 'dash', 'ru', '2', 'stratum+tcp://eu.emcd.io:8888', now(), now()),
    (1, 'dash', 'ru', '3', 'stratum+tcp://kz.emcd.io:8888', now(), now()),
    (1, 'dash', 'cn', '1', 'stratum+tcp://cn.emcd.io:8888', now(), now()),
    (1, 'dash', 'cn', '2', 'stratum+tcp://eu.emcd.io:8888', now(), now()),
    (1, 'dash', 'cn', '3', 'stratum+tcp://gate.emcd.io:8888', now(), now()),
    (1, 'dash', 'us', '1', 'stratum+tcp://us.emcd.io:8888', now(), now()),
    (1, 'dash', 'us', '2', 'stratum+tcp://eu.emcd.io:8888', now(), now()),
    (1, 'dash', 'us', '3', 'stratum+tcp://gate.emcd.io:8888', now(), now()),
    (1, 'dash', 'ir', '1', 'stratum+tcp://ir.emcd.io:8888', now(), now()),
    (1, 'dash', 'kz', '1', 'stratum+tcp://kz.emcd.io:8888', now(), now()),
    (1, 'dash', 'kz', '2', 'stratum+tcp://gate.emcd.io:8888', now(), now()),
    (1, 'dash', 'kz', '3', 'stratum+tcp://eu.emcd.io:8888', now(), now()),

    (1, 'etc', 'eu', '1', 'stratum+tcp://eu.emcd.io:7878', now(), now()),
    (1, 'etc', 'eu', '2', 'stratum+tcp://eu2.emcd.io:7878', now(), now()),
    (1, 'etc', 'eu', '3', 'stratum+tcp://gate.emcd.io:7878', now(), now()),
    (1, 'etc', 'ru', '1', 'stratum+tcp://gate.emcd.io:7878', now(), now()),
    (1, 'etc', 'ru', '2', 'stratum+tcp://eu.emcd.io:7878', now(), now()),
    (1, 'etc', 'ru', '3', 'stratum+tcp://kz.emcd.io:7878', now(), now()),
    (1, 'etc', 'cn', '1', 'stratum+tcp://cn.emcd.io:7878', now(), now()),
    (1, 'etc', 'cn', '2', 'stratum+tcp://eu.emcd.io:7878', now(), now()),
    (1, 'etc', 'cn', '3', 'stratum+tcp://gate.emcd.io:7878', now(), now()),
    (1, 'etc', 'us', '1', 'stratum+tcp://us.emcd.io:7878', now(), now()),
    (1, 'etc', 'us', '2', 'stratum+tcp://eu.emcd.io:7878', now(), now()),
    (1, 'etc', 'us', '3', 'stratum+tcp://gate.emcd.io:7878', now(), now()),
    (1, 'etc', 'ir', '1', 'stratum+tcp://ir.emcd.io:7878', now(), now()),
    (1, 'etc', 'kz', '1', 'stratum+tcp://kz.emcd.io:7878', now(), now()),
    (1, 'etc', 'kz', '2', 'stratum+tcp://gate.emcd.io:7878', now(), now()),
    (1, 'etc', 'kz', '3', 'stratum+tcp://eu.emcd.io:7878', now(), now()),

    (1, 'doge', 'eu', '1', 'stratum+tcp://eu.emcd.io:3434', now(), now()),
    (1, 'doge', 'eu', '2', 'stratum+tcp://eu2.emcd.io:3434', now(), now()),
    (1, 'doge', 'eu', '3', 'stratum+tcp://gate.emcd.io:3434', now(), now()),
    (1, 'doge', 'ru', '1', 'stratum+tcp://gate.emcd.io:3434', now(), now()),
    (1, 'doge', 'ru', '2', 'stratum+tcp://eu.emcd.io:3434', now(), now()),
    (1, 'doge', 'ru', '3', 'stratum+tcp://kz.emcd.io:3434', now(), now()),
    (1, 'doge', 'cn', '1', 'stratum+tcp://cn.emcd.io:3434', now(), now()),
    (1, 'doge', 'cn', '2', 'stratum+tcp://eu.emcd.io:3434', now(), now()),
    (1, 'doge', 'cn', '3', 'stratum+tcp://gate.emcd.io:3434', now(), now()),
    (1, 'doge', 'us', '1', 'stratum+tcp://us.emcd.io:3434', now(), now()),
    (1, 'doge', 'us', '2', 'stratum+tcp://eu.emcd.io:3434', now(), now()),
    (1, 'doge', 'us', '3', 'stratum+tcp://gate.emcd.io:3434', now(), now()),
    (1, 'doge', 'ir', '1', 'stratum+tcp://ir.emcd.io:3434', now(), now()),
    (1, 'doge', 'kz', '1', 'stratum+tcp://kz.emcd.io:3434', now(), now()),
    (1, 'doge', 'kz', '2', 'stratum+tcp://gate.emcd.io:3434', now(), now()),
    (1, 'doge', 'kz', '3', 'stratum+tcp://eu.emcd.io:3434', now(), now());

