// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: protocol/referral/referral_accounting.proto

package referral

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AccountingReferralService_GetReferralsStatistic_FullMethodName = "/referral.AccountingReferralService/GetReferralsStatistic"
)

// AccountingReferralServiceClient is the client API for AccountingReferralService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountingReferralServiceClient interface {
	// Statistics of income by referral programs
	GetReferralsStatistic(ctx context.Context, in *GetReferralsStatisticRequest, opts ...grpc.CallOption) (*GetReferralsStatisticResponse, error)
}

type accountingReferralServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountingReferralServiceClient(cc grpc.ClientConnInterface) AccountingReferralServiceClient {
	return &accountingReferralServiceClient{cc}
}

func (c *accountingReferralServiceClient) GetReferralsStatistic(ctx context.Context, in *GetReferralsStatisticRequest, opts ...grpc.CallOption) (*GetReferralsStatisticResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReferralsStatisticResponse)
	err := c.cc.Invoke(ctx, AccountingReferralService_GetReferralsStatistic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountingReferralServiceServer is the server API for AccountingReferralService service.
// All implementations must embed UnimplementedAccountingReferralServiceServer
// for forward compatibility
type AccountingReferralServiceServer interface {
	// Statistics of income by referral programs
	GetReferralsStatistic(context.Context, *GetReferralsStatisticRequest) (*GetReferralsStatisticResponse, error)
	mustEmbedUnimplementedAccountingReferralServiceServer()
}

// UnimplementedAccountingReferralServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAccountingReferralServiceServer struct {
}

func (UnimplementedAccountingReferralServiceServer) GetReferralsStatistic(context.Context, *GetReferralsStatisticRequest) (*GetReferralsStatisticResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReferralsStatistic not implemented")
}
func (UnimplementedAccountingReferralServiceServer) mustEmbedUnimplementedAccountingReferralServiceServer() {
}

// UnsafeAccountingReferralServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountingReferralServiceServer will
// result in compilation errors.
type UnsafeAccountingReferralServiceServer interface {
	mustEmbedUnimplementedAccountingReferralServiceServer()
}

func RegisterAccountingReferralServiceServer(s grpc.ServiceRegistrar, srv AccountingReferralServiceServer) {
	s.RegisterService(&AccountingReferralService_ServiceDesc, srv)
}

func _AccountingReferralService_GetReferralsStatistic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReferralsStatisticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountingReferralServiceServer).GetReferralsStatistic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountingReferralService_GetReferralsStatistic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountingReferralServiceServer).GetReferralsStatistic(ctx, req.(*GetReferralsStatisticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountingReferralService_ServiceDesc is the grpc.ServiceDesc for AccountingReferralService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountingReferralService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "referral.AccountingReferralService",
	HandlerType: (*AccountingReferralServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetReferralsStatistic",
			Handler:    _AccountingReferralService_GetReferralsStatistic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocol/referral/referral_accounting.proto",
}
