// Code generated by mockery v2.46.3. DO NOT EDIT.

package swap

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metadata "google.golang.org/grpc/metadata"

	swap "code.emcdtech.com/b2b/swap/protocol/swap"
)

// MockSwapService_StatusServer is an autogenerated mock type for the SwapService_StatusServer type
type MockSwapService_StatusServer struct {
	mock.Mock
}

type MockSwapService_StatusServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSwapService_StatusServer) EXPECT() *MockSwapService_StatusServer_Expecter {
	return &MockSwapService_StatusServer_Expecter{mock: &_m.Mock}
}

// Context provides a mock function with given fields:
func (_m *MockSwapService_StatusServer) Context() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// MockSwapService_StatusServer_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockSwapService_StatusServer_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockSwapService_StatusServer_Expecter) Context() *MockSwapService_StatusServer_Context_Call {
	return &MockSwapService_StatusServer_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockSwapService_StatusServer_Context_Call) Run(run func()) *MockSwapService_StatusServer_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSwapService_StatusServer_Context_Call) Return(_a0 context.Context) *MockSwapService_StatusServer_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSwapService_StatusServer_Context_Call) RunAndReturn(run func() context.Context) *MockSwapService_StatusServer_Context_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function with given fields: m
func (_m *MockSwapService_StatusServer) RecvMsg(m any) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(any) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSwapService_StatusServer_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type MockSwapService_StatusServer_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m any
func (_e *MockSwapService_StatusServer_Expecter) RecvMsg(m interface{}) *MockSwapService_StatusServer_RecvMsg_Call {
	return &MockSwapService_StatusServer_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *MockSwapService_StatusServer_RecvMsg_Call) Run(run func(m any)) *MockSwapService_StatusServer_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(any))
	})
	return _c
}

func (_c *MockSwapService_StatusServer_RecvMsg_Call) Return(_a0 error) *MockSwapService_StatusServer_RecvMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSwapService_StatusServer_RecvMsg_Call) RunAndReturn(run func(any) error) *MockSwapService_StatusServer_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: _a0
func (_m *MockSwapService_StatusServer) Send(_a0 *swap.StatusResponse) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*swap.StatusResponse) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSwapService_StatusServer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockSwapService_StatusServer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 *swap.StatusResponse
func (_e *MockSwapService_StatusServer_Expecter) Send(_a0 interface{}) *MockSwapService_StatusServer_Send_Call {
	return &MockSwapService_StatusServer_Send_Call{Call: _e.mock.On("Send", _a0)}
}

func (_c *MockSwapService_StatusServer_Send_Call) Run(run func(_a0 *swap.StatusResponse)) *MockSwapService_StatusServer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*swap.StatusResponse))
	})
	return _c
}

func (_c *MockSwapService_StatusServer_Send_Call) Return(_a0 error) *MockSwapService_StatusServer_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSwapService_StatusServer_Send_Call) RunAndReturn(run func(*swap.StatusResponse) error) *MockSwapService_StatusServer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function with given fields: _a0
func (_m *MockSwapService_StatusServer) SendHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SendHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSwapService_StatusServer_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type MockSwapService_StatusServer_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *MockSwapService_StatusServer_Expecter) SendHeader(_a0 interface{}) *MockSwapService_StatusServer_SendHeader_Call {
	return &MockSwapService_StatusServer_SendHeader_Call{Call: _e.mock.On("SendHeader", _a0)}
}

func (_c *MockSwapService_StatusServer_SendHeader_Call) Run(run func(_a0 metadata.MD)) *MockSwapService_StatusServer_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *MockSwapService_StatusServer_SendHeader_Call) Return(_a0 error) *MockSwapService_StatusServer_SendHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSwapService_StatusServer_SendHeader_Call) RunAndReturn(run func(metadata.MD) error) *MockSwapService_StatusServer_SendHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function with given fields: m
func (_m *MockSwapService_StatusServer) SendMsg(m any) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(any) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSwapService_StatusServer_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type MockSwapService_StatusServer_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m any
func (_e *MockSwapService_StatusServer_Expecter) SendMsg(m interface{}) *MockSwapService_StatusServer_SendMsg_Call {
	return &MockSwapService_StatusServer_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *MockSwapService_StatusServer_SendMsg_Call) Run(run func(m any)) *MockSwapService_StatusServer_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(any))
	})
	return _c
}

func (_c *MockSwapService_StatusServer_SendMsg_Call) Return(_a0 error) *MockSwapService_StatusServer_SendMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSwapService_StatusServer_SendMsg_Call) RunAndReturn(run func(any) error) *MockSwapService_StatusServer_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function with given fields: _a0
func (_m *MockSwapService_StatusServer) SetHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSwapService_StatusServer_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type MockSwapService_StatusServer_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *MockSwapService_StatusServer_Expecter) SetHeader(_a0 interface{}) *MockSwapService_StatusServer_SetHeader_Call {
	return &MockSwapService_StatusServer_SetHeader_Call{Call: _e.mock.On("SetHeader", _a0)}
}

func (_c *MockSwapService_StatusServer_SetHeader_Call) Run(run func(_a0 metadata.MD)) *MockSwapService_StatusServer_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *MockSwapService_StatusServer_SetHeader_Call) Return(_a0 error) *MockSwapService_StatusServer_SetHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSwapService_StatusServer_SetHeader_Call) RunAndReturn(run func(metadata.MD) error) *MockSwapService_StatusServer_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function with given fields: _a0
func (_m *MockSwapService_StatusServer) SetTrailer(_a0 metadata.MD) {
	_m.Called(_a0)
}

// MockSwapService_StatusServer_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type MockSwapService_StatusServer_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *MockSwapService_StatusServer_Expecter) SetTrailer(_a0 interface{}) *MockSwapService_StatusServer_SetTrailer_Call {
	return &MockSwapService_StatusServer_SetTrailer_Call{Call: _e.mock.On("SetTrailer", _a0)}
}

func (_c *MockSwapService_StatusServer_SetTrailer_Call) Run(run func(_a0 metadata.MD)) *MockSwapService_StatusServer_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *MockSwapService_StatusServer_SetTrailer_Call) Return() *MockSwapService_StatusServer_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSwapService_StatusServer_SetTrailer_Call) RunAndReturn(run func(metadata.MD)) *MockSwapService_StatusServer_SetTrailer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSwapService_StatusServer creates a new instance of MockSwapService_StatusServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSwapService_StatusServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSwapService_StatusServer {
	mock := &MockSwapService_StatusServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
