version: '3.8'

services:
  postgres:
    container_name: postgres-coin
    image: postgres:16.1
    restart: always
    ports:
      - "5438:5432"
    environment:
      POSTGRES_DB: coin
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user", "-d", "coin" ]
      interval: 1s
      timeout: 5s
      retries: 10

  flyway:
    container_name: flyway-coin
    image: flyway/flyway:latest
    command:
      -url=jdbc:postgresql://postgres-coin:5432/coin -user=user -password=password -validateMigrationNaming="true" -connectRetries=60 migrate
    volumes:
      - ../../migrations:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy

  vault:
    container_name: vault-coin
    image: hashicorp/vault:latest
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: testtoken
    ports:
      - "8200:8200"
    privileged: true

networks:
  default:
    name: network-coin-service
