// Code generated by mockery v2.46.3. DO NOT EDIT.

package swapWithdraw

import mock "github.com/stretchr/testify/mock"

// MockUnsafeSwapWithdrawServiceServer is an autogenerated mock type for the UnsafeSwapWithdrawServiceServer type
type MockUnsafeSwapWithdrawServiceServer struct {
	mock.Mock
}

type MockUnsafeSwapWithdrawServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsafeSwapWithdrawServiceServer) EXPECT() *MockUnsafeSwapWithdrawServiceServer_Expecter {
	return &MockUnsafeSwapWithdrawServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedSwapWithdrawServiceServer provides a mock function with given fields:
func (_m *MockUnsafeSwapWithdrawServiceServer) mustEmbedUnimplementedSwapWithdrawServiceServer() {
	_m.Called()
}

// MockUnsafeSwapWithdrawServiceServer_mustEmbedUnimplementedSwapWithdrawServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedSwapWithdrawServiceServer'
type MockUnsafeSwapWithdrawServiceServer_mustEmbedUnimplementedSwapWithdrawServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedSwapWithdrawServiceServer is a helper method to define mock.On call
func (_e *MockUnsafeSwapWithdrawServiceServer_Expecter) mustEmbedUnimplementedSwapWithdrawServiceServer() *MockUnsafeSwapWithdrawServiceServer_mustEmbedUnimplementedSwapWithdrawServiceServer_Call {
	return &MockUnsafeSwapWithdrawServiceServer_mustEmbedUnimplementedSwapWithdrawServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedSwapWithdrawServiceServer")}
}

func (_c *MockUnsafeSwapWithdrawServiceServer_mustEmbedUnimplementedSwapWithdrawServiceServer_Call) Run(run func()) *MockUnsafeSwapWithdrawServiceServer_mustEmbedUnimplementedSwapWithdrawServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnsafeSwapWithdrawServiceServer_mustEmbedUnimplementedSwapWithdrawServiceServer_Call) Return() *MockUnsafeSwapWithdrawServiceServer_mustEmbedUnimplementedSwapWithdrawServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUnsafeSwapWithdrawServiceServer_mustEmbedUnimplementedSwapWithdrawServiceServer_Call) RunAndReturn(run func()) *MockUnsafeSwapWithdrawServiceServer_mustEmbedUnimplementedSwapWithdrawServiceServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUnsafeSwapWithdrawServiceServer creates a new instance of MockUnsafeSwapWithdrawServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeSwapWithdrawServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeSwapWithdrawServiceServer {
	mock := &MockUnsafeSwapWithdrawServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
