// Code generated by mockery v2.43.2. DO NOT EDIT.

package repository

import (
	context "context"

	model "code.emcdtech.com/b2b/swap/model"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"

	transactor "code.emcdtech.com/emcd/sdk/pg"
)

// MockWithdraw is an autogenerated mock type for the Withdraw type
type MockWithdraw struct {
	mock.Mock
}

type MockWithdraw_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWithdraw) EXPECT() *MockWithdraw_Expecter {
	return &MockWithdraw_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, withdraw
func (_m *MockWithdraw) Add(ctx context.Context, withdraw *model.Withdraw) error {
	ret := _m.Called(ctx, withdraw)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Withdraw) error); ok {
		r0 = rf(ctx, withdraw)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWithdraw_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockWithdraw_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - withdraw *model.Withdraw
func (_e *MockWithdraw_Expecter) Add(ctx interface{}, withdraw interface{}) *MockWithdraw_Add_Call {
	return &MockWithdraw_Add_Call{Call: _e.mock.On("Add", ctx, withdraw)}
}

func (_c *MockWithdraw_Add_Call) Run(run func(ctx context.Context, withdraw *model.Withdraw)) *MockWithdraw_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Withdraw))
	})
	return _c
}

func (_c *MockWithdraw_Add_Call) Return(_a0 error) *MockWithdraw_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWithdraw_Add_Call) RunAndReturn(run func(context.Context, *model.Withdraw) error) *MockWithdraw_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function with given fields: ctx, filter
func (_m *MockWithdraw) Find(ctx context.Context, filter *model.WithdrawFilter) (model.Withdraws, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 model.Withdraws
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.WithdrawFilter) (model.Withdraws, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.WithdrawFilter) model.Withdraws); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Withdraws)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.WithdrawFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWithdraw_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockWithdraw_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *model.WithdrawFilter
func (_e *MockWithdraw_Expecter) Find(ctx interface{}, filter interface{}) *MockWithdraw_Find_Call {
	return &MockWithdraw_Find_Call{Call: _e.mock.On("Find", ctx, filter)}
}

func (_c *MockWithdraw_Find_Call) Run(run func(ctx context.Context, filter *model.WithdrawFilter)) *MockWithdraw_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.WithdrawFilter))
	})
	return _c
}

func (_c *MockWithdraw_Find_Call) Return(_a0 model.Withdraws, _a1 error) *MockWithdraw_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWithdraw_Find_Call) RunAndReturn(run func(context.Context, *model.WithdrawFilter) (model.Withdraws, error)) *MockWithdraw_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindOne provides a mock function with given fields: ctx, filter
func (_m *MockWithdraw) FindOne(ctx context.Context, filter *model.WithdrawFilter) (*model.Withdraw, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindOne")
	}

	var r0 *model.Withdraw
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.WithdrawFilter) (*model.Withdraw, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.WithdrawFilter) *model.Withdraw); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Withdraw)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.WithdrawFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWithdraw_FindOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOne'
type MockWithdraw_FindOne_Call struct {
	*mock.Call
}

// FindOne is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *model.WithdrawFilter
func (_e *MockWithdraw_Expecter) FindOne(ctx interface{}, filter interface{}) *MockWithdraw_FindOne_Call {
	return &MockWithdraw_FindOne_Call{Call: _e.mock.On("FindOne", ctx, filter)}
}

func (_c *MockWithdraw_FindOne_Call) Run(run func(ctx context.Context, filter *model.WithdrawFilter)) *MockWithdraw_FindOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.WithdrawFilter))
	})
	return _c
}

func (_c *MockWithdraw_FindOne_Call) Return(_a0 *model.Withdraw, _a1 error) *MockWithdraw_FindOne_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWithdraw_FindOne_Call) RunAndReturn(run func(context.Context, *model.WithdrawFilter) (*model.Withdraw, error)) *MockWithdraw_FindOne_Call {
	_c.Call.Return(run)
	return _c
}

// Runner provides a mock function with given fields: ctx
func (_m *MockWithdraw) Runner(ctx context.Context) transactor.PgxQueryRunner {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Runner")
	}

	var r0 transactor.PgxQueryRunner
	if rf, ok := ret.Get(0).(func(context.Context) transactor.PgxQueryRunner); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(transactor.PgxQueryRunner)
		}
	}

	return r0
}

// MockWithdraw_Runner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Runner'
type MockWithdraw_Runner_Call struct {
	*mock.Call
}

// Runner is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWithdraw_Expecter) Runner(ctx interface{}) *MockWithdraw_Runner_Call {
	return &MockWithdraw_Runner_Call{Call: _e.mock.On("Runner", ctx)}
}

func (_c *MockWithdraw_Runner_Call) Run(run func(ctx context.Context)) *MockWithdraw_Runner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockWithdraw_Runner_Call) Return(_a0 transactor.PgxQueryRunner) *MockWithdraw_Runner_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWithdraw_Runner_Call) RunAndReturn(run func(context.Context) transactor.PgxQueryRunner) *MockWithdraw_Runner_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, withdraw, filter, partial
func (_m *MockWithdraw) Update(ctx context.Context, withdraw *model.Withdraw, filter *model.WithdrawFilter, partial *model.WithdrawPartial) error {
	ret := _m.Called(ctx, withdraw, filter, partial)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Withdraw, *model.WithdrawFilter, *model.WithdrawPartial) error); ok {
		r0 = rf(ctx, withdraw, filter, partial)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWithdraw_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockWithdraw_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - withdraw *model.Withdraw
//   - filter *model.WithdrawFilter
//   - partial *model.WithdrawPartial
func (_e *MockWithdraw_Expecter) Update(ctx interface{}, withdraw interface{}, filter interface{}, partial interface{}) *MockWithdraw_Update_Call {
	return &MockWithdraw_Update_Call{Call: _e.mock.On("Update", ctx, withdraw, filter, partial)}
}

func (_c *MockWithdraw_Update_Call) Run(run func(ctx context.Context, withdraw *model.Withdraw, filter *model.WithdrawFilter, partial *model.WithdrawPartial)) *MockWithdraw_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Withdraw), args[2].(*model.WithdrawFilter), args[3].(*model.WithdrawPartial))
	})
	return _c
}

func (_c *MockWithdraw_Update_Call) Return(_a0 error) *MockWithdraw_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWithdraw_Update_Call) RunAndReturn(run func(context.Context, *model.Withdraw, *model.WithdrawFilter, *model.WithdrawPartial) error) *MockWithdraw_Update_Call {
	_c.Call.Return(run)
	return _c
}

// WithinTransaction provides a mock function with given fields: ctx, txFn
func (_m *MockWithdraw) WithinTransaction(ctx context.Context, txFn func(context.Context) error) error {
	ret := _m.Called(ctx, txFn)

	if len(ret) == 0 {
		panic("no return value specified for WithinTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, txFn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWithdraw_WithinTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithinTransaction'
type MockWithdraw_WithinTransaction_Call struct {
	*mock.Call
}

// WithinTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - txFn func(context.Context) error
func (_e *MockWithdraw_Expecter) WithinTransaction(ctx interface{}, txFn interface{}) *MockWithdraw_WithinTransaction_Call {
	return &MockWithdraw_WithinTransaction_Call{Call: _e.mock.On("WithinTransaction", ctx, txFn)}
}

func (_c *MockWithdraw_WithinTransaction_Call) Run(run func(ctx context.Context, txFn func(context.Context) error)) *MockWithdraw_WithinTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *MockWithdraw_WithinTransaction_Call) Return(_a0 error) *MockWithdraw_WithinTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWithdraw_WithinTransaction_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *MockWithdraw_WithinTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// WithinTransactionWithOptions provides a mock function with given fields: ctx, txFn, opts
func (_m *MockWithdraw) WithinTransactionWithOptions(ctx context.Context, txFn func(context.Context) error, opts pgx.TxOptions) error {
	ret := _m.Called(ctx, txFn, opts)

	if len(ret) == 0 {
		panic("no return value specified for WithinTransactionWithOptions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error, pgx.TxOptions) error); ok {
		r0 = rf(ctx, txFn, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWithdraw_WithinTransactionWithOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithinTransactionWithOptions'
type MockWithdraw_WithinTransactionWithOptions_Call struct {
	*mock.Call
}

// WithinTransactionWithOptions is a helper method to define mock.On call
//   - ctx context.Context
//   - txFn func(context.Context) error
//   - opts pgx.TxOptions
func (_e *MockWithdraw_Expecter) WithinTransactionWithOptions(ctx interface{}, txFn interface{}, opts interface{}) *MockWithdraw_WithinTransactionWithOptions_Call {
	return &MockWithdraw_WithinTransactionWithOptions_Call{Call: _e.mock.On("WithinTransactionWithOptions", ctx, txFn, opts)}
}

func (_c *MockWithdraw_WithinTransactionWithOptions_Call) Run(run func(ctx context.Context, txFn func(context.Context) error, opts pgx.TxOptions)) *MockWithdraw_WithinTransactionWithOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error), args[2].(pgx.TxOptions))
	})
	return _c
}

func (_c *MockWithdraw_WithinTransactionWithOptions_Call) Return(_a0 error) *MockWithdraw_WithinTransactionWithOptions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWithdraw_WithinTransactionWithOptions_Call) RunAndReturn(run func(context.Context, func(context.Context) error, pgx.TxOptions) error) *MockWithdraw_WithinTransactionWithOptions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWithdraw creates a new instance of MockWithdraw. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWithdraw(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWithdraw {
	mock := &MockWithdraw{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
